- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
   
  - name: Check if directory exists
    stat:
      path: /AngularFront
    register: repo_stat
    
  - name: Clone repository
    shell: |
      git clone https://github.com/BenAmor1/AngularFront.git /AngularFront
    when: repo_stat.stat.exists == False

  - name: Pull repository
    shell: |
      cd /AngularFront
      git pull 
    when: repo_stat.stat.exists == True
    
  - name: Build the Docker image
    shell: | 
      cd /AngularFront
      docker build . -t angularfront/image
   
  - name: Tag the image
    shell: | 
      cd /AngularFront
      docker tag angularfront/image beffa/project_pfe-2022:angular_frontV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:angular_frontV1
    
